import {
  AfterViewInit,
  ChangeDetectionStrategy,
  ChangeDetectorRef,
  Component,
  ElementRef,
  Input,
  NgZone,
  OnDestroy,
  ViewChild,
} from '@angular/core';

/**
 * What `public/<folder>/manifest.json` has to contain.
 *
 * It is generated by `npm run hero:manifest` from the frames in the folder, so
 * nobody has to count 240 files by hand.
 */
export interface FrameManifest {
  /** Number of frames. */
  frameCount: number;
  /** File name with `{n}` where the (zero-padded) frame number goes. */
  pattern: string;
  /** Digits of the frame number: `frame_0001.webp` → 4. */
  pad: number;
  /** First frame number; Blender starts at 1 by default. */
  start: number;
  fps: number;
  loop: boolean;
  /** Intrinsic size of a frame, used to reserve the space before loading. */
  width: number;
  height: number;
}

type SequenceState = 'loading' | 'playing' | 'placeholder';

/**
 * Plays a frame-by-frame animation (the Blender export of Mr. Bip) on a canvas.
 *
 * **Why frames on a canvas and not a video.** The render has a transparent
 * background so it can sit on top of the hero glow. WebM with alpha does not
 * play in Safari and HEVC with alpha does not play anywhere else; a WebP per
 * frame keeps the transparency in every browser.
 *
 * **Why a manifest.** Until the frames exist, the folder is empty. Without a
 * `manifest.json` the component shows its placeholder (the projected content)
 * instead of an empty box or a failed request per frame.
 *
 * Playback stops when the hero leaves the screen or the tab is hidden, and with
 * `prefers-reduced-motion` it shows a single still frame.
 */
@Component({
  selector: 'app-frame-sequence',
  standalone: true,
  templateUrl: './frame-sequence.component.html',
  styleUrl: './frame-sequence.component.css',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class FrameSequenceComponent implements AfterViewInit, OnDestroy {
  /** Folder inside `public/`, without leading or trailing slash: `mr_bip/hero`. */
  @Input({ required: true }) folder!: string;

  /** Accessible description of the animation. */
  @Input() label = '';

  @ViewChild('canvas') private canvasRef?: ElementRef<HTMLCanvasElement>;

  state: SequenceState = 'loading';
  aspectRatio = '4 / 5';

  private manifest?: FrameManifest;
  private frames: HTMLImageElement[] = [];
  private rafId = 0;
  private lastTick = 0;
  private current = 0;
  private visible = true;
  private observer?: IntersectionObserver;
  private destroyed = false;

  constructor(
    private readonly host: ElementRef<HTMLElement>,
    private readonly zone: NgZone,
    private readonly cdr: ChangeDetectorRef,
  ) {}

  ngAfterViewInit(): void {
    if (typeof window === 'undefined') return;
    void this.init();
  }

  ngOnDestroy(): void {
    this.destroyed = true;
    cancelAnimationFrame(this.rafId);
    this.observer?.disconnect();
    document.removeEventListener('visibilitychange', this.onVisibilityChange);
  }

  private async init(): Promise<void> {
    const manifest = await this.loadManifest();
    if (!manifest) {
      this.setState('placeholder');
      return;
    }
    this.manifest = manifest;
    this.aspectRatio = `${manifest.width} / ${manifest.height}`;
    this.cdr.markForCheck();

    const reduced = window.matchMedia('(prefers-reduced-motion: reduce)').matches;
    try {
      // With reduced motion only the middle frame is needed: downloading the
      // whole sequence to show one picture would waste the visitor's data.
      const indexes = reduced
        ? [Math.floor(manifest.frameCount / 2)]
        : Array.from({ length: manifest.frameCount }, (_, i) => i);
      this.frames = await Promise.all(indexes.map((i) => this.loadFrame(i)));
    } catch (error) {
      console.error('[frame-sequence] a frame failed to load, showing placeholder', error);
      this.setState('placeholder');
      return;
    }
    if (this.destroyed) return;

    this.setState('playing');
    // The canvas only exists once the state says so: wait for the view.
    requestAnimationFrame(() => {
      this.sizeCanvas();
      this.draw(0);
      if (!reduced && this.frames.length > 1) this.startLoop();
    });
  }

  private async loadManifest(): Promise<FrameManifest | null> {
    try {
      const response = await fetch(`${this.folder}/manifest.json`, { cache: 'no-cache' });
      if (!response.ok) return null;
      const data = (await response.json()) as Partial<FrameManifest>;
      return this.isValidManifest(data) ? data : null;
    } catch {
      // No manifest (or a dev server answering index.html): nothing to play yet.
      return null;
    }
  }

  private isValidManifest(data: Partial<FrameManifest>): data is FrameManifest {
    return (
      typeof data.frameCount === 'number' && data.frameCount > 0 &&
      typeof data.pattern === 'string' && data.pattern.includes('{n}') &&
      typeof data.pad === 'number' &&
      typeof data.start === 'number' &&
      typeof data.fps === 'number' && data.fps > 0 &&
      typeof data.width === 'number' && typeof data.height === 'number'
    );
  }

  private loadFrame(index: number): Promise<HTMLImageElement> {
    const m = this.manifest!;
    const number = String(m.start + index).padStart(m.pad, '0');
    const src = `${this.folder}/${m.pattern.replace('{n}', number)}`;
    const img = new Image();
    img.decoding = 'async';
    img.src = src;
    return img.decode().then(() => img);
  }

  private startLoop(): void {
    this.zone.runOutsideAngular(() => {
      this.observer = new IntersectionObserver(([entry]) => {
        this.visible = entry.isIntersecting;
        if (this.visible) this.tick(performance.now());
      });
      this.observer.observe(this.host.nativeElement);
      document.addEventListener('visibilitychange', this.onVisibilityChange);
      this.rafId = requestAnimationFrame((t) => this.tick(t));
    });
  }

  private readonly onVisibilityChange = (): void => {
    if (!document.hidden && this.visible) this.tick(performance.now());
  };

  private tick(now: number): void {
    cancelAnimationFrame(this.rafId);
    if (!this.visible || document.hidden || this.destroyed) return;

    const m = this.manifest!;
    const interval = 1000 / m.fps;
    if (now - this.lastTick >= interval) {
      this.lastTick = now;
      const next = this.current + 1;
      if (next >= this.frames.length) {
        if (!m.loop) return;
        this.current = 0;
      } else {
        this.current = next;
      }
      this.draw(this.current);
    }
    this.rafId = requestAnimationFrame((t) => this.tick(t));
  }

  private sizeCanvas(): void {
    const canvas = this.canvasRef?.nativeElement;
    if (!canvas || !this.manifest) return;
    canvas.width = this.manifest.width;
    canvas.height = this.manifest.height;
  }

  private draw(index: number): void {
    const canvas = this.canvasRef?.nativeElement;
    const ctx = canvas?.getContext('2d');
    const frame = this.frames[index];
    if (!canvas || !ctx || !frame) return;
    ctx.clearRect(0, 0, canvas.width, canvas.height);
    ctx.drawImage(frame, 0, 0, canvas.width, canvas.height);
  }

  private setState(state: SequenceState): void {
    this.state = state;
    this.cdr.markForCheck();
  }
}
